name: Lint and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request' }}
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.head_ref }}
          # ref: ${{ github.event.pull_request.head.ref }}
          # repository: ${{ github.event.pull_request.head.repo.full_name }}
          # token: ${{ secrets.GH_PAT_REPO_WORKFLOW_SCOPE }}

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build
      - name: format
        run: npm run format
      - name: lint
        run: npm run lint
      - name: package
        run: npm run package
      - name: test
        run: npm run test
